AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LayerName:
    Type: String

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-layer-cfncli
    Description: "AWS Lambda Layer for CloudFormation CLI with python3.8"
    Author: Eduardo Rodrigues
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['layer','lambda','cloudformation','python', 'aws']
    HomePageUrl: https://github.com/eduardomourar/aws-lambda-layer-cfncli
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/eduardomourar/aws-lambda-layer-cfncli

Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Layer for CloudFormation CLI with python3.8

Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      ContentUri: ./layer.zip
      CompatibleRuntimes: 
        - python3.7
        - python3.8
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain

Outputs:
  LayerVersionArn:
    Description: ARN for the published Layer version
    Value: !Ref LambdaLayer
    Export:
      Name: !Sub 'LayerVersionArn-${AWS::StackName}'
